/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        IRON_KIT_CATEGORY: 'Iron Kit',
        IRONKIT_INIT: 'init iron kit',
        IRONKIT_SETSERVODEGREE: 'set servo %1 degree %2',
        IRONKIT_SETMOTORSPEED: 'set motor %1 direction %2 speed %3',
        IRONKIT_FORWARD: 'forward',
        IRONKIT_BACKWARD: 'backward',
        IRONKIT_STOPMOTOR: 'break motor %1',
        IRONKIT_SETRGBLEDCOLOR: '设置RGB LED %1 颜色为 %2',
        IRONKIT_ALL: 'all',
        IRONKIT_LEFT: 'left',
        IRONKIT_RIGHT: 'right',
        IRONKIT_SETBUZZER: 'Buzzer play %1',
        IRONKIT_SOUND_CONNECT: 'connect',
        IRONKIT_SOUND_DISCONNECT: 'disconnect',
        IRONKIT_SOUND_BUTTON: 'button',
        IRONKIT_SOUND_MODE: 'mode',
        IRONKIT_SOUND_SUPERRISE: 'superrise',
        IRONKIT_SOUND_OHOH: 'ohoh',
        IRONKIT_SOUND_OHOH2: 'ohoh2',
        IRONKIT_SOUND_CUTE: 'cute',
        IRONKIT_SOUND_HAPPY: 'happy',
        IRONKIT_SOUND_SAD: 'sad',
        IRONKIT_SOUND_SAD2: 'sad2',
        IRONKIT_PS2READDATA: 'PS2 read data',
        IRONKIT_PS2GETBUTTON: 'PS2 %1 button is pressed?',
        IRONKIT_PS2_UP: 'up',
        IRONKIT_PS2_DOWN: 'down',
        IRONKIT_PS2_LEFT: 'left',
        IRONKIT_PS2_RIGHT: 'right',
        IRONKIT_PS2_TRIANGLE: 'triangle',
        IRONKIT_PS2_CIRCLE: 'circle',
        IRONKIT_PS2_CROSS: 'cross',
        IRONKIT_PS2_SQUARE: 'square',
        IRONKIT_PS2_SELECT: 'select',
        IRONKIT_PS2_START: 'start',
        IRONKIT_PS2GETJOYSTICK: 'PS2 get joystick %1',
        IRONKIT_RGBULTRASONICINIT: 'RGB ultrasonic init data pin %1 RGB pin %2',
        IRONKIT_RGBULTRASONICSETCOLORSTYLE: 'set rgb ultrasonic %1 LED color %2 style %3',
        IRONKIT_NONE: 'none',
        IRONKIT_BREATHING: 'breathing',
        IRONKIT_ROTATE: 'rotate',
        IRONKIT_FLASH: 'flash',
        IRONKIT_RGBULTRASONICREADDISTANCE: 'rgb ultrasonic read distance'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        IRON_KIT_CATEGORY: '工程车套件',
        IRONKIT_INIT: '初始化工程车套件',
        IRONKIT_SETSERVODEGREE: '设置舵机 %1 角度 %2',
        IRONKIT_SETMOTORSPEED: '设置电机 %1 方向 %2 速度 %3',
        IRONKIT_FORWARD: '正转',
        IRONKIT_BACKWARD: '倒转',
        IRONKIT_STOPMOTOR: '电机 %1 刹车',
        IRONKIT_SETRGBLEDCOLOR: '设置RGB LED %1 颜色为 %2',
        IRONKIT_ALL: '全部',
        IRONKIT_LEFT: '左边',
        IRONKIT_RIGHT: '右边',
        IRONKIT_SETBUZZER: '蜂鸣器播放 %1',
        IRONKIT_SOUND_CONNECT: '连接',
        IRONKIT_SOUND_DISCONNECT: '断开连接',
        IRONKIT_SOUND_BUTTON: '按键',
        IRONKIT_SOUND_MODE: '模式',
        IRONKIT_SOUND_SUPERRISE: '惊讶',
        IRONKIT_SOUND_OHOH: '哦哦',
        IRONKIT_SOUND_OHOH2: '哦哦2',
        IRONKIT_SOUND_CUTE: '可爱',
        IRONKIT_SOUND_HAPPY: '开心',
        IRONKIT_SOUND_SAD: '伤心',
        IRONKIT_SOUND_SAD2: '伤心2',
        IRONKIT_PS2READDATA: 'PS2读取数据',
        IRONKIT_PS2GETBUTTON: 'PS2 %1 按键被按下?',
        IRONKIT_PS2_UP: '上',
        IRONKIT_PS2_DOWN: '下',
        IRONKIT_PS2_LEFT: '左',
        IRONKIT_PS2_RIGHT: '右',
        IRONKIT_PS2_TRIANGLE: '三角',
        IRONKIT_PS2_CIRCLE: '圆',
        IRONKIT_PS2_CROSS: '叉号',
        IRONKIT_PS2_SQUARE: '方块',
        IRONKIT_PS2_SELECT: '选择',
        IRONKIT_PS2_START: '开始',
        IRONKIT_PS2GETJOYSTICK: 'PS2获取摇杆 %1',
        IRONKIT_RGBULTRASONICINIT: 'RGB超声波传感器初始化 数据引脚 %1 RGB引脚 %2',
        IRONKIT_RGBULTRASONICSETCOLORSTYLE: '设置RGB超声波传感器 %1 LED颜色 %2 样式 %3',
        IRONKIT_NONE: '无',
        IRONKIT_BREATHING: '呼吸',
        IRONKIT_ROTATE: '旋转',
        IRONKIT_FLASH: '闪烁',
        IRONKIT_RGBULTRASONICREADDISTANCE: 'RGB超声波传感器读取距离'
    });
    return Blockly;
}

exports = addMsg;
